# Generated by Django 4.1.3 on 2022-11-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="time",
            field=models.TextField(default="22:13 PM"),
        ),
    ]
