# Generated by Django 4.1.3 on 2022-11-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_comments_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="social.post"
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="time",
            field=models.TextField(default="22:34 PM"),
        ),
    ]
