# Generated by Django 4.1.3 on 2022-11-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_alter_comments_post_alter_comments_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="time",
            field=models.TextField(default="04/11/2022"),
        ),
    ]
